// Re-export SDK types for convenience (using /client to avoid Node.js deps)
export type {
  Session,
  Message,
  UserMessage,
  AssistantMessage,
  Part,
  TextPart,
  ToolPart,
  ReasoningPart,
  FilePart,
  ToolState,
  ToolStatePending,
  ToolStateRunning,
  ToolStateCompleted,
  ToolStateError,
  Project,
  Provider,
  Model,
  Agent,
  Todo,
  Permission,
  FileDiff,
  SessionStatus,
  Event,
} from "@opencode-ai/sdk/client";
